development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: apidb
  pool: 5
  username: shivanik
  password: shivani
test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: apidb
  pool: 5
  username: shivanik
  password: shivani
